<a href="https://colab.research.google.com/github/Gatchplease/Introduction-to-Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and its Operations

In [2]:
import numpy as np
a = np.array ([1,2,3])
print(a)

[1 2 3]


In [19]:
b = np.array([[1,2,3,],[4,5,6,]])
b[0,0] = 7
print(b)


[[7 2 3]
 [4 5 6]]


In [20]:
c = np.array([[1,2,3,],[4,5,6,],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
d =np.full((2,2),4) 
print(d)

[[4 4]
 [4 4]]


In [22]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [23]:
import numpy as np
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[1 5 9]


In [24]:
import numpy as np
f = np.empty((0,10))
print(f)

[]


In [25]:
import numpy as np
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [29]:
import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g)
print(e-g)
print(g-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
