<a href="https://colab.research.google.com/github/Gatchplease/Numerical-Methods/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3. Evaluate the determinant of matrix A using Pivotal Method (Note: Show your pertinent solutions) 20 points##


In [8]:
import numpy as np

In [11]:
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5
