<a href="https://colab.research.google.com/github/Gatchplease/Numerical-Methods/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Determinants of Matrix##

In [4]:
import numpy as np

In [5]:
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
