<a href="https://colab.research.google.com/github/Gatchplease/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and Its Operations

## Python Exercise 2

In [6]:
import numpy as np

a = np.array([[-5,0,],[4,1,]]) 
b = np.array([[6,-3,],[2,3,]])

print(a)
print(b)
print(a+b)
print(b-a)
print(a-b)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[ 1 -3]
 [ 6  4]]
[[11 -3]
 [-2  2]]
[[-11   3]
 [  2  -2]]
